name: Create PR
on:
  push:
    branches:
      - develop  # Trigger workflow on push to develop branch
permissions:
  pull-requests: write
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
     - run: gh pr create --base main --head develop --title "PR created" --body "Automated Creation" --assignee brcelso
       env:
          GITHUB_TOKEN: ${{ secrets.secrets_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}
            
