name: Create PR

on:
  push:
    branches:
      - develop  # Trigger workflow on push to develop branch

permissions:
  pull-requests: write
  contents: write  # Needed for accessing repository content

jobs:
  build:
    name: Check and Create Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checkout the code before creating the PR

    - name: Check for new commits
      id: check-commits
      run: |
          git fetch origin main
          if [ "$(git rev-list --count develop ^origin/main)" -eq 0 ]; then
            echo "No new commits between develop and main"
            echo "no_updates=true" >> $GITHUB_ENV
          else
            echo "New commits found"
            echo "no_updates=false" >> $GITHUB_ENV
          fi

    - name: Create Pull Request
      if: env.no_updates == 'false'
      run: |
          gh pr create --base main --head develop --title "PR created" --body "Automated Creation" --assignee brcelso
      env:
        GH_TOKEN: ${{ secrets.secrets_PAT }}  # Use personal access token (PAT)

      
    - name: Output Result
      run: |
          if [ "${{ env.no_updates }}" == "true" ]; then
            echo "No new updates between branches, skipping PR creation."
          else
            echo "Pull request successfully created from develop to main."
          fi
