name: Create PR

on:
  push:
    branches:
      - develop  # Trigger workflow on push to develop branch

permissions:
  pull-requests: write
  contents: write  # Needed for accessing repository content

jobs:
  build:
    name: Check and Create Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checkout the code before creating the PR

    - name: Check for new commits
      run: |
        git fetch origin main
        NEW_COMMITS=$(git log --oneline origin/main..origin/develop)
        if [ -z "$NEW_COMMITS" ]; then
          echo "No new commits between main and develop. Exiting..."
          exit 0  # Exit successfully when no new commits
        else
          echo "New commits found, proceeding to create PR."
        fi

    - name: Create Pull Request
      if: success()  # Only run if new commits are found
      run: |
        gh pr create --base main --head develop --title "PR created" --body "Automated Creation" --assignee brcelso
      env:
        GH_TOKEN: ${{ secrets.secrets_PAT }}  # Use personal access token (PAT)
