name: Create PR from Develop to Main

on:
  push:
    branches:
      - develop  # Trigger workflow on push to develop branch

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt-get update
          sudo apt-get install gh -y

      # Step 3: Authenticate with Personal Access Token (secrets_PAT)
      - name: Authenticate GitHub CLI with secrets_PAT
        run: |
          echo "${{ secrets.secrets_PAT }}" | gh auth login --with-token

      # Step 4: Check if PR already exists (Optional Improvement)
      - name: Check if PR already exists
        run: |
          gh pr list --base main --head develop --repo ${{ github.repository }} --json number,title --jq '.[] | "\(.number): \(.title)"'
        continue-on-error: true

      # Step 5: Create Pull Request (if it doesn't exist)
      - name: Create Pull Request
        run: |
          gh pr create --base main --head develop --title "First PR" --body "Manual Test" --assignee brcelso

      # Step 6: Output Success Message
      - name: Success Message
        run: echo "Pull request successfully created from develop to main."
