name: Create PR

on:
  push:
    branches:
      - develop  # Trigger workflow on push to develop branch

permissions:
  pull-requests: write
  contents: write  # Needed for accessing repository content

jobs:
  build:
    name: Check and Create Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checkout the code before creating the PR

    - name: Check for new commits
      run: |
        git fetch origin main
        NEW_COMMITS=$(git log --oneline origin/main..origin/develop)
        if [ -z "$NEW_COMMITS" ]; then
          echo "No new commits between main and develop. Exiting..."
          exit 0  # Exit successfully when no new commits
        else
          echo "New commits found, proceeding to check for existing PR."
        fi

    - name: Check for existing Pull Request
      id: check_pr
      run: |
        PR_URL=$(gh pr list --base main --head develop --json url --jq '.[0].url')
        if [ -n "$PR_URL" ]; then
          echo "Pull request already exists: $PR_URL"
          echo "pr_exists=true" >> $GITHUB_ENV  # Set environment variable to true
        else
          echo "No existing pull request found."
          echo "pr_exists=false" >> $GITHUB_ENV  # Set environment variable to false
        fi
      env:
        GH_TOKEN: ${{ secrets.secrets_PAT }}  # Use personal access token (PAT)

    - name: Create Pull Request
      if: env.pr_exists == 'false'  # Only run if no existing PR is found
      run: |
        gh pr create --base main --head develop --title "PR created" --body "Automated Creation" --assignee brcelso
      env:
        GH_TOKEN: ${{ secrets.secrets_PAT }}  # Use personal access token (PAT)

 

  
